
package ragnaroggame;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JLabel;



public class RogMenu extends javax.swing.JFrame {

    /**
     * Creates new form RogMenu
     */
    public RogMenu() {
        initComponents();
    }
        ArrayList<Monster> monsters = new ArrayList<Monster>();
        Novice novice1 = new Novice("ice",100,100);
        Novice pet = new Novice("Salmon",20,20);
        double hpMon = 0;
        int count = 0;
        public void madeMon(){
            double monHp, monAtja;
        for(int i = 0; i < 5 ;i++ ){
            monHp = Math.random()*400.0;
            monAtja  = Math.random()*40;
            Monster monja = new Monster(monHp,monAtja);
            monsters.add(monja);
        }
        
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static String printNovice(Novice novice){
        String hp = "Name: "+
                novice.getName()+"\nHealth: "+String.format("%.0f", novice.getHealth())
                +"/"+String.format("%.0f",novice.maxHealth);
        String exp = "\nExp: "+
                String.format("%.02f",novice.getExp());
         String hungry = "\nHungry: "+
                String.format("%.02f",novice.getHungry());
          String attackSkill = "\nAttack skill: "+
                String.format("%.02f",novice.getSkill());
           
        return hp+exp+hungry+attackSkill;
    }
        public static String printHealth(Novice novice){
        String hp = "Health: "+String.format("%.0f",novice.getHealth())
                +"/"+String.format("%.0f",novice.maxHealth);
       
        return hp;
    }
    
    
        
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Map");
        jButton1.setPreferredSize(new java.awt.Dimension(70, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 40, 100, 50);

        jButton3.setText("Attack");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 190, 100, 50);

        jButton4.setText("Summon");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(490, 190, 100, 50);

        jButton5.setText("Trainning");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(280, 40, 100, 50);

        jButton6.setText("Eat");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(490, 40, 100, 50);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Run", "Walk", "Swim" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 120, 100, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FriedChicken", "RainbowCake", "MysteryBread" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(490, 120, 100, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 270, 340, 220);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 270, 310, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ragnaroggame/pic/bg6.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, 4, 770, 520);

        setBounds(0, 0, 777, 561);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //trainning
        String type = jComboBox1.getSelectedItem().toString();
        switch(type){
            case "Walk" : 
                        jLabel2.setIcon(new ImageIcon(getClass().getResource("pic/run.gif")));
                        novice1.excercise(new Trainning(0));
                        jTextArea1.setText(printNovice(novice1));
                        break;
            case "Run" : 
                        jLabel2.setIcon(new ImageIcon(getClass().getResource("pic/walk.gif")));
                        novice1.excercise(new Trainning(1));
                        jTextArea1.setText(printNovice(novice1));
    
                        break;
            case "Swim" : 
                        jLabel2.setIcon(new ImageIcon(getClass().getResource("pic/swim.gif")));
                        novice1.excercise(new Trainning(2));
                        jTextArea1.setText(printNovice(novice1));
                        break;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //food
                 String type = jComboBox2.getSelectedItem().toString();
        switch(type){
            case "FriedChicken" : 
                        jLabel2.setIcon(new ImageIcon(getClass().getResource("pic/chicken.gif")));
                        novice1.eat(new Food(0));
                        jTextArea1.setText(printNovice(novice1));
                        break;
            case "RainbowCake" : 
                        jLabel2.setIcon(new ImageIcon(getClass().getResource("pic/cake.gif")));
                        novice1.eat(new Food(1));
                        jTextArea1.setText(printNovice(novice1));
    
                        break;
            case "MysteryBread" : 
                        jLabel2.setIcon(new ImageIcon(getClass().getResource("pic/bread.gif")));
                        novice1.eat(new Food(2));
                        jTextArea1.setText(printNovice(novice1));
                        break;
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //attack
        jLabel2.setIcon(new ImageIcon(getClass().getResource("pic/attack.gif")));
		
                
                if(hpMon <= 0){
                    hpMon = (Math.random()*400.0);
                }
                
            hpMon -= novice1.attackSkill;    
            if(hpMon <= 0){
                hpMon = 0;
                count++;    
            }        
        jTextArea1.setText("\nHp of Monster :" + String.format("%.2f",hpMon)+ "\nCount Monster :" + String.format("%d",count));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jLabel2.setIcon(new ImageIcon(getClass().getResource("pic/pet1.gif")));
        jTextArea1.setText(printNovice(pet));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //map
        jLabel2.setIcon(new ImageIcon(getClass().getResource("pic/map2.jpg")));
        this.madeMon();
        String allData=" ",data;
        for(Monster monjas : monsters)
            allData = allData + monjas.showData();  
        jTextArea1.setText(allData);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RogMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RogMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RogMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RogMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RogMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
